config/routes.rb
Rails.application.routes.draw do
  
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'users/:id'    => 'works#show'
  get    'users/:id/edit_basic_info',to:'users#edit_basic_info',as:'edit_basic_info'
  patch  'users/:id/update_basic_info' , to: 'users#update_basic_info',as:'update_basic_info'
  post   'works/:id', to: 'works#edit_works',as:'edit_works'
  
  resources :works
  # resources :worksがあるので修正はいらなかったですね。そのままコントローラーのアクションcreateの追加とビューの名前変更で行けると思います！
  resources :users do
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  def show
    @user = User.find(params[:id])
     if    current_user.admin? 
     elsif current_user != User.find(params[:id]) 
           redirect_to(root_url) 
           flash[:warning] = "ほかのユーザにはアクセスできません"
     end
      if  !params[:first_day].nil?
          @first_day = Date.parse(params[:first_day])
      else
          @first_day = Date.new(Date.today.year, Date.today.month)
      end
            @last_day = @first_day.end_of_month
            @works = @user.works.where(day: @first_day..@last_day)
        unless  @user.works.find_by(day: @first_day)
                @first_day.all_month.each do |day|
                Work.create!(day: day,user_id: @user.id)
                end
        end
  end
  
    
  def edit
    @user = User.find(params[:id])
     if current_user.admin? 
     elsif current_user != User.find(params[:id]) 

        redirect_to(root_url) 
            flash[:warning] = "ほかのユーザにはアクセスできません"
     end
      if  !params[:first_day].nil?
          @first_day = Date.parse(params[:first_day])
      else
          @first_day = Date.new(Date.today.year, Date.today.month)
      end
            @last_day = @first_day.end_of_month
            @works = @user.works.where(day: @first_day..@last_day)
        unless  @user.works.find_by(day: @first_day)
                @first_day.all_month.each do |day|
                Work.create!(day: day,user_id: @user.id)
                end
        end
  end
  
  
  
  def update
    @user = current_user
    work = Work.find(params[:id])
    if params[:button_type] == "start" && work.attendance_time.nil?
      work.update(attendance_time: Time.zone.now.to_s(:long))
      flash[:success] = "今日も一日頑張りましょう！"
      elsif params[:button_type] == "end" && work.leaving_time.nil?
      work.update(leaving_time: Time.zone.now.to_s(:long))
      flash[:success] = "お疲れ様でした！"
    end
    redirect_to work_url(@user)
    
  end
  
  
  
  
  def edit_works
    @user = User.find(params[:id])
      works_params.each do |id, time|
        work = Work.find(id)
          if work.day > Date.current && !current_user.admin?
          elsif time["attendance_time"].blank? && time["leaving_time"].blank?
          elsif time["attendance_time"].blank? || time["leaving_time"].blank?
            flash[:warning] = '一部編集が無効となった項目があります。'
          elsif time["attendance_time"].to_s > time["leaving_time"].to_s
            flash[:warning] = '出社時間より退社時間が早い項目がありました'
          else
                work.update_attributes(time)
                  flash[:success] = '勤怠時間を更新しました。なお本日以降の更新はできません。'
          end
      end 
    redirect_to edit_work_path(@user, params:{ id: @user.id, first_day: params[:first_day]})
  end
  
  
  
  
  
   private
   
    def works_params
      params.permit(works: [:attendance_time, :leaving_time, :remarks])[:works]
    end

end

app/views/works/_basic_information.html.erb
<table class="table table-bordered">
  <tr>
    <td class="col-md-4 col-lg-4">
      <%= link_to "◀︎",work_url(params: { id: @user.id, first_day: @first_day.prev_month }), style:"color:white", class: 'btn btn-default btn-primary' %>
      <%= @first_day.strftime("%Y年%m月") %>　勤怠管理表
      <%= link_to "▶︎",work_url(params: { id: @user.id, first_day: @first_day.next_month }), style:"color:white", class: 'btn btn-default btn-primary' %>
    </td>
     <td class="col-lg-2">初日　<%= @first_day.beginning_of_month.strftime("%m月%d日") %></td>
       <td class="col-lg-2">締め　<%= @last_day.strftime("%m月%d日") %></td>
         <td class="col-md-1 col-lg-1">コード</td>
  </tr>
</table>

app/views/works/_user_information.html.erb
<table class="table table-bordered">
 <tr>
  <td class="col-lg-2"><%= @user.name %></td>
  <td class="col-lg-1"><%= @user.affiliation %></td>
  <td class="col-lg-2">勤務日数合計　<%= work_count(@works)%>日</td>
  <td class="col-lg-2">勤務時間合計　<%= month_work_time(@works) %></td>
  <td class="col-lg-2">指定勤務時間　<%= specified_time(@works)%></td>
  <td class="col-lg-2">基本時間　<%= basic_time(@works)%></td>
 </tr>
</table>

app/views/works/edit.html.erb
 <% provide(:title, @user.name) %>



<h1><%= @user.name %>の勤怠情報編集</h1>


　<div class="row">
  
  <%= render 'user_information'%>
    
      
        
  <table class="table-striped table-bordered">
    <tr>
      <th class="col-lg-2">日付</th>
      <th class="col-lg-2">曜日</th>
      <th class="col-lg-2">出社時間編集</th>
      <th class="col-lg-2">退社時間編集</th>
      <th class="col-lg-2">在社時間</th>
      <th class="col-lg-2">備考</th>
    </tr>
  </table>
  
  <%= form_for(@user, url: edit_works_path, method: :post) do |f| %>
     

  <table class="table-striped table-bordered">
    <% @works.each do |work| %>
      <tr>
        <td class="col-lg-2"><%= work.day.month %>月<%= work.day.day %>日</td>
        <td class="col-lg-2"><%= %w(日 月 火 水 木 金 土 日)[work.day.wday] %></td>
        <td class="col-lg-2">
          <%= fields_for "works[]", work do |fi| %>
          <%= fi.time_field :attendance_time, {class: 'form-control'} %>
          <% end %>
        </td>
        <td class="col-lg-2">
          <%= fields_for "works[]", work do |fi| %>
          <%= fi.time_field :leaving_time, {class: 'form-control'}  %>
          <% end %>
        </td>
        <td class="col-lg-2"><%= day_work_time(work) %></td>
        <td class="col-lg-2"><%= work.remarks %></td>
      </tr>
    <%end%>
  </table>
  
  <center>
    <%= f.submit "編集内容で更新", style:"width:300px", class: "btn btn-primary" %>
    <%= link_to "キャンセル", edit_work_path( @user, params:{first_day: @first_day }), style: "width:300px", class: "btn btncancel btn-default" %>
  </center>
  <% end %>
  
</div>

app/views/works/show.html.erb
<% provide(:title, @user.name) %>


<div class="row">
  
  <%= render 'user_information'%>
    <%= render 'basic_information'%>
      <%if current_user.try(:admin?)%>
        <center>
          <%= link_to "当該ユーザーの勤怠情報を編集", edit_work_path(date:@works), class: "btn btn-lg btn-primary" %>
          <%= link_to "当該ユーザーの基本情報を編集", edit_basic_info_path(@user), class: "btn btn-lg btn-primary" %>
        </center>
      <%end%>
        

  <table class="table-striped table-bordered">
    <tr>
      <th class="col-lg-1">日付</th>
      <th class="col-lg-1">曜日</th>
      <th class="col-lg-1">出退勤 ボタン</th>
      <th class="col-lg-1">出社(時)</th>
      <th class="col-lg-1">出社(分)</th>
      <th class="col-lg-1">退社(時)</th>
      <th class="col-lg-1">退社(分)</th>
      <th class="col-lg-1">在社時間</th>
      <th class="col-lg-1">備考</th>
    </tr>
  </table>
  
  
  <table class="table-striped table-bordered">
    <% @works.each do |work| %>
      <tr>
        <td class="col-lg-1"><%= work.day.month %>月<%= work.day.day %>日</td>
        <td class="col-lg-1"><%= %w(日 月 火 水 木 金 土 日)[work.day.wday] %></td>
        <td class="col-lg-1">
          <% if work.day == Date.today && work.attendance_time.nil? %> 
            <%= button_to "出社", work_path(work, button_type: "start"), class: "btn btn-default btn-min btn-block", :method => :patch %>
          <% end %>
          <% if work.day == Date.today && work.attendance_time && work.leaving_time.nil? %>
            <%= button_to "退社", work_path(work, button_type: "end"), class: "btn btn-default btn-min btn-block", :method => :patch %>
          <% end %>
        </td>
        <td class="col-lg-1"><%= work.attendance_time.hour if work.attendance_time %></td>
        <td class="col-lg-1"><%= work.attendance_time.min if work.attendance_time %></td>
        <td class="col-lg-1"><%= work.leaving_time.hour if work.leaving_time %></td>
        <td class="col-lg-1"><%= work.leaving_time.min if work.leaving_time %></td>
        <td class="col-lg-1"><%= day_work_time(work) %></td>
        <td class="col-lg-1"><%= work.remarks %></td>
      </tr>
    <%end%>
  </table>
  
</div>