config/routes.rb
Rails.application.routes.draw do
  
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'users/:id'    => 'works#show'
  get    'users/:id/edit_basic_info',to:'users#edit_basic_info',as:'edit_basic_info'
  patch  'users/:id/update_basic_info' , to: 'users#update_basic_info',as:'update_basic_info'
  post   'works/:id', to: 'works#edit_works',as:'edit_works'
  
  resources :works
  # resources :worksがあるので修正はいらなかったですね。そのままコントローラーのアクションcreateの追加とビューの名前変更で行けると思います！
  resources :users do
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   Create by <a href="https://www.facebook.com/hiroki.suganuma" target="_blank" >hiroki suganuma</a>
  </small>
    <ul>
      <li><%= link_to "このサイトについて",about_path %></li>
  　</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠システム", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "勤怠を編集", edit_work_path(current_user)%></li>
            <li><%= link_to "勤怠入力画面", user_url(current_user) %></li>
              <%if current_user.try(:admin?)%>
                <li><%= link_to "ユーザー覧", users_path ,id:"menu" %></li>
                <li><%= link_to "基本情報の更新", edit_basic_info_path(current_user) %></li>
              <%end%>
            <li><%= link_to "アカウント情報の更新", edit_user_path(current_user) %></li>
            <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        </ul>
          <% else %>
            <li><%= link_to "ログイン", login_path ,id:"menu" %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
 <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html